// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomService.Data;

#nullable disable

namespace RoomService.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20250812050651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomService.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BreakfastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DinnerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LunchPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Rooms_Name");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BreakfastPrice = 5500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 7500m,
                            Discount = 10m,
                            Features = "WiFi,19m²,Air Conditioning,Smart TV,Sea View,Private Balcony",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751611214/Deluxe_Double_evv1bi.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751620602/512776456_kbl9gc.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512785655_khsxtc.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512785654_wckoc2.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512785660_xsq4ki.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512776444_bwh65n.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512785661_d7hhnk.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634312/512785657_zwvltz.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634313/512776423_tdasme.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634314/512785656_rv4j9u.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634315/512785659_gf29av.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634315/512785662_oi04wx.jpg",
                            LunchPrice = 7000m,
                            Name = "Deluxe Double",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Airport Pickup,Non-refundable,Pay the property before arrival",
                            Price = 35000m,
                            RoomNumbers = "101,102,103,104,105",
                            TotalRooms = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BreakfastPrice = 6500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 8000m,
                            Discount = 5m,
                            Features = "WiFi,19m²,Smart TV,City View",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634969/512657784_ugzgua.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634968/512657779_viohnb.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634968/512657665_o48np4.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634968/512657706_lqcku2.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634968/512657744_hf1ol5.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634969/512657710_u3czsh.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634969/512657404_gwaon4.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634970/512657641_hopnrb.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634970/512657636_gfdf8t.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634970/512657754_pbidju.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634970/512657797_rka41a.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634971/512657804_oeolbp.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634971/512657805_nne36c.jpg,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634976/512657818_omxdgg.jpg",
                            LunchPrice = 7500m,
                            Name = "Deluxe King",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Non-refundable,Pay the property before arrival",
                            Price = 45000m,
                            RoomNumbers = "301,302,303,304",
                            TotalRooms = 4,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BreakfastPrice = 5000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 6500m,
                            Discount = 15m,
                            Features = "WiFi,Smart TV,Mini Fridge,Room Service,Garden View",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650546/26166157_gljocd.webp,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650546/35365136_n3tgkc.webp,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650547/37344774_lcgsvj.webp,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650547/37344776_czwlvu.webp,https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650548/37344738_ziucqp.webp",
                            LunchPrice = 6000m,
                            Name = "Standard Double",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Late Checkout,Airport Pickup,Non-refundable,Pay the property before arrival",
                            Price = 25000m,
                            RoomNumbers = "201",
                            TotalRooms = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
