// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomService.Data;

#nullable disable

namespace RoomService.Migrations
{
    [DbContext(typeof(RoomContext))]
    partial class RoomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomService.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BreakfastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DinnerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LunchPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Rooms_Name");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BreakfastPrice = 5500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 7500m,
                            Discount = 10m,
                            Features = "WiFi,19m²,Air Conditioning,Smart TV,Sea View,Private Balcony",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751611214/Deluxe_Double_evv1bi.jpg",
                            LunchPrice = 7000m,
                            Name = "Deluxe Double",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Airport Pickup,Non-refundable,Pay the property before arrival",
                            Price = 35000m,
                            RoomNumbers = "101,102,103,104,105",
                            TotalRooms = 5,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BreakfastPrice = 6500m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 8000m,
                            Discount = 5m,
                            Features = "WiFi,19m²,Smart TV,City View",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751634969/512657784_ugzgua.jpg",
                            LunchPrice = 7500m,
                            Name = "Deluxe King",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Non-refundable,Pay the property before arrival",
                            Price = 45000m,
                            RoomNumbers = "301,302,303,304",
                            TotalRooms = 4,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BreakfastPrice = 5000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DinnerPrice = 6500m,
                            Discount = 15m,
                            Features = "WiFi,Smart TV,Mini Fridge,Room Service,Garden View",
                            ImageUrls = "https://res.cloudinary.com/dfnqhfdyw/image/upload/v1751650546/26166157_gljocd.webp",
                            LunchPrice = 6000m,
                            Name = "Standard Double",
                            NumberOfGuests = 2,
                            Options = "Breakfast Included,Late Checkout,Airport Pickup,Non-refundable,Pay the property before arrival",
                            Price = 25000m,
                            RoomNumbers = "201",
                            TotalRooms = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
